spring.datasource.url=jdbc:postgresql://localhost:5432/genau
spring.datasource.username=postgres
spring.datasource.password=0506
spring.datasource.driver-class-name=org.postgresql.Driver


#
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hongsick0787@gmail.com
spring.mail.password=nrdj nhtn aozm hbts
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000



cloudconvert.api.key= eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiY2Q2MjJiMTY2YzQ1NGJlMzA3MmVmMzI0MTRjMmQ2ODJhMjFlZDNkNDNhZTBkNzY5MGY2MTc3YjdiMjgzYTdkYzg3ZWU0MTM0Nzg2YzEzY2MiLCJpYXQiOjE3NDc5MDg2OTEuNTQ3NzAyLCJuYmYiOjE3NDc5MDg2OTEuNTQ3NzA0LCJleHAiOjQ5MDM1ODIyOTEuNTQxNiwic3ViIjoiNzIwMDQwMDAiLCJzY29wZXMiOlsidXNlci5yZWFkIiwidXNlci53cml0ZSIsInRhc2sucmVhZCIsInRhc2sud3JpdGUiLCJ3ZWJob29rLnJlYWQiLCJ3ZWJob29rLndyaXRlIiwicHJlc2V0LnJlYWQiLCJwcmVzZXQud3JpdGUiXX0.DGG8FmKVNPJNv11pBP-u5tvTV3IiLQHXy5JuOUQWy4h_R9Cvjj8ylCvDNHUwh7Cl6WqhkNGOtE8X0JYP-iqjLR1-lnzf3Qb5ehO7YoapIFAvYJpy-K4-0qVGaQInahbzaVsHTuutYW3PCeAPQ5YoHpcJudOF7jPfJhFXVWAL7anM6PxnB4IgxwLKlo8I2Wfw1Ij46YwvzRdy4ihoRp5Z5kQFOSsUwO4c2TbhKWNyRtwL7PcFJLB8bb6TlKlyp30c3qSKHKoMNBl9SpFWQrljwj64x5x3-QOaHmm3G_T-eVsPwepyRPAgv3S-57t303_UPHVPOJeeMPWMgv8XFgGonglxnpIL4WlmtsY_vaOEYyzdjryoj7njW5UeI11F81FO1g9SY1wQ6xroUXKkLi93EHyozhDPSaWpYCm8wg7d1XO7G2u-V-1690AfgxGIjXRo2b6Lmu61VQiyLLfMqBkMJScR18oXh_B25mV_wcgoZStxNorvB7uwmse2W5iczUXHHJxWeE3dN8AR0gJ9gNgHmk6B1yW3gCN0VL10eMOlkJhBdapoIMhRNzDL6BFwtqz7YJuSyMJwou_sQNf2DxyWM6Ob36UZKEUDKzLm8MWKVYB9mZu6T6CLdfvgTYhVAQHunet7OODutVda-3wWTX7U1SLfUueTB_jI1sHprzpWYHU