spring.datasource.url=jdbc:postgresql://localhost:5432/genau
spring.datasource.username=postgres
spring.datasource.password=0506
spring.datasource.driver-class-name=org.postgresql.Driver


#
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hongsick0787@gmail.com
spring.mail.password=nrdj nhtn aozm hbts
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000



cloudconvert.api.key=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZjNkMWVlMTgwZjMxMGMxYzM0ODNjMzkwOGFjNTMyZTM2YzhhY2QyMzk1YzhlMjhkNzU0ZWU0YmNjZjc2YmRlMWYyMTgwYjRhMmM1NmQ5MWEiLCJpYXQiOjE3NDcxNDA5NjIuNDk2OTE4LCJuYmYiOjE3NDcxNDA5NjIuNDk2OTIsImV4cCI6NDkwMjgxNDU2Mi40OTEwNTMsInN1YiI6IjcxOTEyNDUzIiwic2NvcGVzIjpbInVzZXIucmVhZCIsInRhc2sucmVhZCIsInVzZXIud3JpdGUiLCJ0YXNrLndyaXRlIiwicHJlc2V0LndyaXRlIiwicHJlc2V0LnJlYWQiLCJ3ZWJob29rLndyaXRlIiwid2ViaG9vay5yZWFkIl19.WZS7YgTqXnBNX4YYxo6izfqt8Aup59hFNFiAV4DuFp7knuwxws9sQsE-Gx-BrHqnVQpTW8N5s1NwaAfVjwNV2G-bcb6yvyolowQXeEqFJHhKaqRilbTJvDUGf5dT6hrZ76Jhn-KlIcd4R0fzYKzFdWBgt5KZjGtwiK99C5-HHLPP4qu82ZWg3c-wPlqPKA9--UYslXhNstJ3AU9cD3UBWlUwKtJHswgKiagXRzcin6MhG8VEu_zMTqm-Q0Ldp6DL8V9ZV1sSRaXeO7w-J4v29ugFaXxWpgvgSoRzsLu0tqTDSsYK7x2Sg5JInAISQO34EHQ4StX8gwxvMEcJFsDLPByokeY0yJEpohK6MogKN65d6N3JBd_zyy8YMNNEAo_8gD4ePBBsijOM-haZZLF1ylt3MyitqXVNyMciQARaQkNBLanTL0MnQOtYQrwWRZ4RepXesMq-MZfgCHUYv1yc62UK7BiKwbiq27dV2zIShm3Pi-EXkSHLTtwIGXs08kAdvE5WSHIYK61yodpke5Rbk02pxyVveplNoZafnN1A0O-kJeFIsCXXecs5ayhCh0ag30Ah8iVdnZBplhKT3JfqnKdm958hG0WYvkNjf2qlfT-Qetz7kQaQWSDyfCx0a6iEnVYg8Cl8SFxeFQpLLiKG32oLlAq7AotAdC4fsFpduX4